#!/usr/bin/python3

import sys

def factorize(number):
    for i in range(2, number):
        if number % i == 0:
            return f"{number}={number//i}*{i}"
    return f"{number} is a prime number"

def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            factorization = factorize(number)
            print(factorization)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: factors <file>")
        print("where <file> is a file containing natural numbers to factor.")
        sys.exit(1)
    filename = sys.argv[1]
    main(filename)
